### ISSUE TITLE
please add link to tools/updates to side panel in Tools section

### ISSUE THREAD

**Issue by doktor5000** [agallou/mageia-app-db#258]
Subject says it all, http://mageia.madb.org/tools/updates should be available in the left side panel in the tools sections, maybe as "QA update candidates overview".

The current link "Update candidates" in section Latest to http://mageia.madb.org/rpm/list/listtype/updates_testing does not provide the same information.

**Comment by stormi** [comment]
Done, currently deploying.

**Comment by doktor5000** [comment]
Thanks :+1:
